### ISSUE TITLE
[feature request] Add ordinal support

### ISSUE THREAD

**Issue by xd009642** [Matthew-Maclean/english-numbers#1]
So 1 becomes first, 2 second, 3 third etc. I imagine it would be added to the formatting struct as something disabled by default.

**Comment by Matthew-Maclean** [comment]
It's been a while since I looked at this repo, but I think that adding ordinal formatting would require passing a formatting argument all the way down into the `Group`, `Hundreds`, and `Tens`, to modify the word they `build` into, and also require some way of identifying which is the last number in the sequence, so that it can be modified (so that "110" doesn't become "One Hundredth and Tenth"). This could probably be remedied if the words were built all at once rather than by their individual structs, but at that point it's basically a full rewrite.

I don't really want to do this to a two year old repo, but if you want to do it I'll probably accept the PR. If you opt for the full rewrite route, then you should probably just make your own repo, since there will be so little of my original code left.
